//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Btvn1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int examId { get; set; }
        public string examName { get; set; }
        public double examMark { get; set; }
        public System.DateTime examDate { get; set; }
        public int stuId { get; set; }
        public int couId { get; set; }
    }
}
