//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Btvn1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stuId { get; set; }
        public string stuPass { get; set; }
        public string stuName { get; set; }
        public string stuAddress { get; set; }
        public int stuPhone { get; set; }
        public string stuEmail { get; set; }
        public int deptId { get; set; }
    }
}
